---
deployment:
  tasks:
    - export DEPLOYPATH=/home/haif1056/public_html/
    - /bin/cp -r public/* $DEPLOYPATH
    - export DEPLOYPATH=/home/haif1056/laravel/
    - /bin/cp -r !(public)/* $DEPLOYPATH


